### ISSUE TITLE
필터박스 열린 상태에서  클릭 하면 나타났다 사라졌다 하는 현상

### ISSUE THREAD

**Issue by Seungwoo321** [vue-pivottable/vue3-pivottable#36]
## 문제 
- 해당 이슈로 필터박스 UI 내부의 이벤트 동작이 안됨 

## 원인
- 아래 스타일 주석 처리시 필터박스는 동작하지만 드래그 할 때 열린 상태가 유지되는 문제가 있음 
 
```css
.sortable-chosen .pvtFilterBox {
  display: none !important;
}
```
